// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHw-tpFSmW55GT4OYW6_2SySN1JMzQ7MQ',
    appId: '1:850945219885:web:93659667cab405dc1b47a4',
    messagingSenderId: '850945219885',
    projectId: 'virtigo-exe2',
    authDomain: 'virtigo-exe2.firebaseapp.com',
    storageBucket: 'virtigo-exe2.firebasestorage.app',
    measurementId: 'G-91FVVGNX7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASsQe0TbtIDq-BjJRkzmc7pLNIh3s1vuw',
    appId: '1:850945219885:android:d0b9bd1a6230dc6d1b47a4',
    messagingSenderId: '850945219885',
    projectId: 'virtigo-exe2',
    storageBucket: 'virtigo-exe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-JjYhzY1K_HYwOg-JP9CQ6GMeq4zRuuw',
    appId: '1:850945219885:ios:2bc2342e781cb6f71b47a4',
    messagingSenderId: '850945219885',
    projectId: 'virtigo-exe2',
    storageBucket: 'virtigo-exe2.firebasestorage.app',
    iosBundleId: 'com.example.virtigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-JjYhzY1K_HYwOg-JP9CQ6GMeq4zRuuw',
    appId: '1:850945219885:ios:2bc2342e781cb6f71b47a4',
    messagingSenderId: '850945219885',
    projectId: 'virtigo-exe2',
    storageBucket: 'virtigo-exe2.firebasestorage.app',
    iosBundleId: 'com.example.virtigo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHw-tpFSmW55GT4OYW6_2SySN1JMzQ7MQ',
    appId: '1:850945219885:web:263e36facb877f701b47a4',
    messagingSenderId: '850945219885',
    projectId: 'virtigo-exe2',
    authDomain: 'virtigo-exe2.firebaseapp.com',
    storageBucket: 'virtigo-exe2.firebasestorage.app',
    measurementId: 'G-LB8QDTK005',
  );
}
